### ISSUE TITLE
Server is not setup to serve?

### ISSUE THREAD

**Issue by vandijkstef** [Maikxx/web-app-from-scratch-18-19#10]
Direct urls or back/forward don't work. Opt for a method that does work, or fix the servers settings.
Routing will be discussed in class next week

**Comment by Maikxx** [comment]
I suppose this is on the Netlify version, correct? I am aware of those issues, there is no way (that I am aware of) that takes a path, like /characters/1 to work on there without serving from a server, since Netlify is looking for an HTML file at that URL. Locally I have no issues with this used method.

Curious to see how we might fix this next week.

**Comment by Maikxx** [comment]
Fixed this in the latest commit.
