### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vandijkstef** [Maikxx/web-app-from-scratch-18-19#9]
I've been doing TS for a few months, please feel free to open up discussion.

In general your application is well structured, I could trace/find most stuff using common sense. A few items that caught my eye:

It might be interesting to create a base class for your `DetailViews`. Most code is duplicate, I'd prefer an untyped/any base class over this duplication.

Additionally, your `interface Props` is defined in each of those files. Some contain an extra ID, you might want to extend.

I wasn't aware of this implicit creation of properties, thanks!
https://github.com/Maikxx/web-app-from-scratch-18-19/blob/fe31f397b2d1055eaf9b725c1b54d0ced29fa985/client/src/ts/views/BookDetailView.ts#L14

Pretty tedious, you might want to create a more abstract sorter that accepts a key (like 'name')
https://github.com/Maikxx/web-app-from-scratch-18-19/blob/master/client/src/ts/sorters/sortCharactersByName.ts

Is async doing anything here?
https://github.com/Maikxx/web-app-from-scratch-18-19/blob/fe31f397b2d1055eaf9b725c1b54d0ced29fa985/client/src/ts/index.ts#L9

Be wary not to over-engineer oneliners
https://github.com/Maikxx/web-app-from-scratch-18-19/blob/master/client/src/ts/utils/reset.ts#L2

**Comment by Maikxx** [comment]
"It might be interesting to create a base class for your `DetailViews`. Most code is duplicate, I'd prefer an untyped/any base class over this duplication."
- Agreed, however this is related to the next point below.

"Additionally, your `interface Props` is defined in each of those files. Some contain an extra ID, you might want to extend."
- I like the explicit way of defining types here better, since in most cases (views and components) there will be no such thing as a BaseProps interface, because they all differ, just because they are the same here now, doesn't mean they will always be, which would require a type restructuring, which I found to be more tedious than doing this.

"Is async doing anything here?"
- Nope, forgot to remove that async part from a previous version.

"Pretty tedious, you might want to create a more abstract sorter that accepts a key (like 'name')"
- Agreed.

"Be wary not to over-engineer oneliners"
- Generally easier for people to have a grasp on what this might do.

**Comment by Maikxx** [comment]
Added solutions to the following feedback points:

* "It might be interesting to create a base class for your `DetailViews`. Most code is duplicate, I'd prefer an untyped/any base class over this duplication."
* "Is async doing anything here?"
* "Pretty tedious, you might want to create a more abstract sorter that accepts a key (like 'name')"
